[tool.poetry]
name = "malthus"
version = "0.1.0"
description = ""
authors = ["George Alexander <george.alexander@arup.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
